services:
  server:
    build:
      context: ../src/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: server
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-filmodb}
      POSTGRES_USER: ${POSTGRES_USER:-filmo_user}
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-filmo_password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - movie-network
    expose:
      - 3000

  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-filmodb}
      POSTGRES_USER: ${DB_USER:-filmo_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-filmo_password}
    networks:
      - movie-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-filmo_user} -d ${POSTGRES_DB:-filmodb}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - movie-network

networks:
  movie-network:

volumes:
  postgres-data:
