name: Update tconst Data

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and process tconst data
        run: |
          chmod +x ./scripts/download_tconst.sh
          ./scripts/download_tconst.sh

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update tconst list"
          file_pattern: "docker/postgres/tconst_list.txt"
